
steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
  with:
    python-version: '3.10'
    cache: 'pip' # caching pip dependencies
- run: pip install -r requests
- run: pip install -r pytelegramapi
- run: pip install -r beautifulsoup4
- run: python pybot.py
- name: Test with pytest
      run:
        pytest
